keywords = {
    'break': 'Break statement',
    'case': 'Case statement',
    'const': 'Constant identifier statement',
    'continue': 'Continue statement',
    'default': 'keyword',
    'do': 'Loop statement',
    'else': 'keyword',
    'for': 'Loop statement',
    'goto': 'keyword',
    'if': 'Condition statement',
    'return': 'Return statement',
    'sizeof': 'keyword',
    'struct': 'keyword',
    'switch': 'Switch statement',
    'unsigned': 'keyword',
    'while': 'Loop statement'
}

datatypes = {
    'bool': 'data type',
    'char': 'data type',
    'double': 'data type',
    'enum': 'data type',
    'float': 'data type',
    'int': 'data type',
    'long': 'data type',
    'short': 'data type',
}

operators = {
    '+': 'Arithmetic operator',
    '-': 'Arithmetic operator',
    '*': 'Arithmetic operator',
    '/': 'Arithmetic operator',
    '%': 'Arithmetic operator',
    '++': 'Arithmetic operator',
    '--': 'Arithmetic operator',
    '==': 'Relational operator',
    '!=': 'Relational operator',
    '<': 'Relational operator',
    '>': 'Relational operator',
    '<=': 'Relational operator',
    '>=': 'Relational operator',
    '&&': 'Logical operator',
    '||': 'Logical operator',
    '!': 'Logical operator',
    '=': 'Assigment operator',
    '+=': 'Assigment operator',
    '-=': 'Assigment operator',
    '*=': 'Assigment operator',
    '/=': 'Assigment operator',
    '%=': 'Assigment operator',
    '<<=': 'Assigment operator',
    '>>=': 'Assigment operator',
    '&=': 'Assigment operator',
    '^=': 'Assigment operator',
    '|=': 'Assigment operator',
}